### ISSUE TITLE
Networking themed gopher

### ISSUE THREAD

**Issue by mdlayher** [egonelbre/gophers#1]
Hey!  You mentioned submitting an issue to the repo on Twitter, so here it is!

I'm looking for a networking-themed Gopher.  Maybe a Gopher holding an ethernet cable?  You had mentioned that it could be similar to: https://github.com/egonelbre/gophers/blob/master/sketch/science/welding.png.

Thanks a ton for these, and for your time!

**Comment by egonelbre** [comment]
Because I couldn't decide which I like more, I uploaded both. :)

Of course, any suggestions/recommendations are welcome. E.g. cable/router color and size.

https://github.com/egonelbre/gophers/blob/master/vector/projects/network.svg
https://github.com/egonelbre/gophers/blob/master/vector/projects/network-side.svg

**Comment by mdlayher** [comment]
Thank you!  I'll look into using one of these for a project shortly!
